export interface MeliProductDetail {
  id: string;
  categoryId: string;
  title: string;
  price: number;
  currency: string;
  stock: number;
  soldQuantity: number;
  status: string;
  condition: string;
  buyingMode: string;
  listingTypeId: string;
  permalink: string;
  thumbnailId: string;
  thumbnail: string;
  pictures: string[];
  sellerSku?: string;
  brand?: string;
  warranty?: string;
  freeShipping: boolean;
  health: number;
  lastUpdated: string;
  description?: string;
  site_id: string | null;
  family_name: string | null;
  family_id: string | null;
  seller_id: number | null;
  user_product_id: string | null;
  official_store_id: number | null;
  base_price: number | null;
  original_price: number | null;
  inventory_id: string | null;
  initial_quantity: number | null;
  available_quantity: number | null;
  sale_terms: unknown[];
  start_time: string | null;
  stop_time: string | null;
  end_time: string | null;
  expiration_time: string | null;
  date_created: string | null;
  last_updated: string | null;
  video_id: string | null;
  accepts_mercadopago: boolean | null;
  shipping: unknown;
  international_delivery_mode: string | null;
  attributes: unknown[];
  variations: unknown[];
  sub_status: unknown[];
  tags: string[];
  catalog_product_id: string | null;
  domain_id: string | null;
  seller_custom_field: string | null;
  parent_item_id: string | null;
  automatic_relist: boolean | null;
  catalog_listing: boolean | null;
  channels: string[];
  warnings: unknown[];
  item_relations: unknown[];
  deal_ids: string[];
}
